DROP TABLE IF EXISTS "USER";
CREATE TABLE "USER"(
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  LOGIN VARCHAR(255) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL
);
INSERT INTO "USER" VALUES
  (1, 'admin', 'admin', 'admin'),
  (2, 'orest', 'oresto', 'oresyto');
SELECT * FROM "USER";

DROP TABLE IF EXISTS "VISIT";
DROP TABLE IF EXISTS "VISITOR";
CREATE TABLE "VISITOR" (
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  CREATE_DATE DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "VISITOR" VALUES
  (1, 'admin'),
  (2, 'orest');
SELECT * FROM "VISITOR";

CREATE TABLE "VISIT" (
  ID INTEGER PRIMARY KEY,
  VISITOR_ID INTEGER REFERENCES "VISITOR"(id),
  DATE_OF_VISIT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO "VISIT" VALUES
  (1, 2),
  (2, 2);
SELECT * FROM "VISIT";