DROP TABLE IF EXISTS "USERS_ROLES";
DROP TABLE IF EXISTS "VISIT";
DROP TABLE IF EXISTS "VISITOR";
DROP TABLE IF EXISTS "USER";
DROP TABLE IF EXISTS "ROLE";
DROP TABLE IF EXISTS "SERVICE";
DROP TABLE IF EXISTS "schema_version";