DROP TABLE IF EXISTS "users_roles";
DROP TABLE IF EXISTS "visit";
DROP TABLE IF EXISTS "visitor";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "role";
DROP TABLE IF EXISTS "service";
DROP TABLE IF EXISTS "salon";
DROP TABLE IF EXISTS "schema_version";