CREATE TABLE IF NOT EXISTS "VISITOR" (
  ID            SERIAL PRIMARY KEY,
  LAST_NAME     VARCHAR(255) NOT NULL,
  FIRST_NAME    VARCHAR(255) NOT NULL,
  MIDDLE_NAME   VARCHAR(255) NOT NULL,
  PHONES        VARCHAR(255),
  EMAIL         VARCHAR(255),
  STATUS        VARCHAR(255) NOT NULL,
  NOTE          VARCHAR(255),
  SEX           VARCHAR(255) NOT NULL,
  DATE_OF_BIRTH DATE         NOT NULL,
  CREATE_DATE   DATE         NOT NULL DEFAULT CURRENT_TIMESTAMP
);
TRUNCATE "VISITOR" CASCADE;
INSERT INTO "VISITOR"(LAST_NAME, FIRST_NAME, MIDDLE_NAME, STATUS, SEX, DATE_OF_BIRTH)  VALUES
  ('lozynskyy', 'orest', 'igorovych', 'gold', 'men', '1986-02-21'),
  ('valko', 'seerhiy', 'mukolayovuch', 'gold', 'men', '1987-03-01');

CREATE TABLE IF NOT EXISTS "SERVICE" (
  ID                    SERIAL PRIMARY KEY,
  NAME                  VARCHAR(255) NOT NULL,
  TYPE                  VARCHAR(255) NOT NULL,
  LAMP_DEFAULT_RESOURCE INTEGER,
  LAMP_TIME_WORKED      INTEGER,
  CREATE_DATE           DATE         NOT NULL DEFAULT CURRENT_TIMESTAMP
);
TRUNCATE "SERVICE" CASCADE;
INSERT INTO "SERVICE" VALUES
  (1, 'Solar1', 'Solar', 10000, 5000),
  (2, 'Solar2', 'Solar', 20000, 3000);

CREATE TABLE IF NOT EXISTS "SALON" (
  ID                    SERIAL PRIMARY KEY,
  NAME                  VARCHAR(255) NOT NULL,
  ADDRESS               VARCHAR(255) NOT NULL,
  CREATE_DATE           DATE         NOT NULL DEFAULT CURRENT_TIMESTAMP
);
TRUNCATE "SALON" CASCADE;
INSERT INTO "SALON" VALUES
  (1, 'Salon1', 'Lviv'),
  (2, 'Salon2', 'Kyiv');

CREATE TABLE IF NOT EXISTS "VISIT" (
  ID            SERIAL PRIMARY KEY,
  VISITOR_ID    INTEGER REFERENCES "VISITOR" (id),
  SERVICE_ID    INTEGER REFERENCES "SERVICE" (id),
  DATE_OF_VISIT DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
TRUNCATE "VISIT" CASCADE;
INSERT INTO "VISIT" VALUES
  (1, 1, 1),
  (2, 1, 2),
  (3, 1, 2),
  (4, 2, 2),
  (5, 2, 2),
  (6, 2, 1);
