CREATE TABLE IF NOT EXISTS "USER" (
  ID            SERIAL PRIMARY KEY,
  USER_NAME     VARCHAR(255)        NOT NULL,
  USER_NICKNAME VARCHAR(255) UNIQUE NOT NULL,
  PASSWORD      VARCHAR(255)        NOT NULL,
  ENABLE        BOOLEAN             NOT NULL
);
TRUNCATE "USER" CASCADE ;
INSERT INTO "USER" VALUES
  (1, 'admin', 'admin', 'admin', TRUE),
  (2, 'orest', 'director', 'oresyto', TRUE),
  (3, 'orest', 'manager', 'oresyto', TRUE);

CREATE TABLE IF NOT EXISTS "ROLE" (
  ID        SERIAL PRIMARY KEY,
  ROLE_NAME VARCHAR(255) UNIQUE NOT NULL
);
TRUNCATE "ROLE" CASCADE;
INSERT INTO "ROLE" VALUES
  (1, 'ROLE_ADMIN'),
  (2, 'ROLE_DIRECTOR'),
  (3, 'ROLE_MANAGER');

CREATE TABLE IF NOT EXISTS "USERS_ROLES" (
  ID      SERIAL PRIMARY KEY,
  USER_ID INTEGER REFERENCES "USER" (id),
  ROLE_ID INTEGER REFERENCES "ROLE" (id)
);
TRUNCATE "USERS_ROLES";
INSERT INTO "USERS_ROLES"(ROLE_ID, USER_ID) VALUES
  (1, 1),
  (1, 2),
  (1, 3),
  (2, 2),
  (2, 3),
  (3, 3);

